# fly.toml file generated for sig-api on 2022-10-17T00:45:47-03:00

app = "sig-api"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  NODE_ENV = "production"
  DATABASE_URL= "postgres://postgres:9fcc9d6e0a1f89a2dc1191c407b80e8118677d7c5e2ed353@sig-api-db.internal:5432/sig_api"
  PGDATABASE = "sig_api"
  PGHOST = "sig-api-db.internal"
  PGPASSWORD = "9fcc9d6e0a1f89a2dc1191c407b80e8118677d7c5e2ed353"
  PGPORT = "5432"
  PGUSER = "postgres"
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
